apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-federation-2
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/maudis73/amq-broker-federation.git'
    path: manifest/amq-federation-2              # Points to the 'app' folder
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mau-amq-fed-broker-2   # Where the app will run
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  # Argo will create the namespace for you!
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
